### ISSUE TITLE
How aggressively do we push for native methods with polyfilling, versus helpers

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/o-dom#1]
For example, should we have `addClass`, `hasClass` and `removeClass` helpers in this module, or should we expect modules to use the [element.classList](https://developer.mozilla.org/en-US/docs/Web/API/element.classList) API, polyfilled as appropriate?

**Comment by chee** [comment]
This is no longer dependended on by any other Origami component, is deprecated and components are now using the web platform.

The things that were a part of this are now native.

`getClosestMatch(element, selector)` => `element.closest(selector)`
`getIndex(element)` => `Array.from(element.parentNode.children).indexOf(element)`
