### ISSUE TITLE
Add wrapElement() ?

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/o-dom#4]
**o-gallery** and **o-table** now both have their own `wrapElement` function, along these lines:

``` javascript
function wrapElement(targetEl, wrapEl) {
    var parentEl = targetEl.parentNode;
    parentEl.insertBefore(wrapEl, targetEl);
    wrapEl.appendChild(targetEl);
}
```

Should we add this to **o-dom**? 

Might be useful to make it use a selector for its first argument, and then make it wrap each matching element with a clone of the `wrapEl`?

Something like this:

``` javascript
oDom.wrapElements('.content a', document.createElement('strong'));
```

**Comment by notlee** [comment]
As this is 4 years old and `o-dom` is now deprecated and `o-table`'s had a few majors, I'm going to close this. Sorry Dan good suggestion 🙈
