### ISSUE TITLE
.matches is not a function error in higher version than 0.3.0 on Firefox 33.0 and older IE version

### ISSUE THREAD

**Issue by laurent-muchacho** [Financial-Times/o-dom#9]
Don't know if this is relevant or should I use the polyfill. But I got an error (.matches) coming from o-dom.getClosestMatch('.fastft-post')

TypeError: a.matches is not a function
http://local.ft.com:5000/fastft/static/8e93c1710a6a3300d74ff3b120c6f285/js/main.js
Line 1

The error occur when the user click on the open button within an article in the stream.

**Comment by kaelig** [comment]
Thanks for reporting this.

Does it work when you load the polyfill service?

**Comment by laurent-muchacho** [comment]
I have not tried yet to use the polyfill service in FastFT will attempt that when fixing a few issue later this week and will report back.

**Comment by laurent-muchacho** [comment]
I've included https://cdn.polyfill.io/v1/polyfill.min.js and the error do not occur  anymore unfortunately will do require a full round of regression testing to make sure it work. 

Could we update the dependencies of the module in http://registry.origami.ft.com/components/o-dom@1.0.0 to reflect that o-dom require the polyfill service to run in the supported browser?

**Comment by kaelig** [comment]
Great!

As a base rule, assume that Origami does require the polyfill service to run.

Closing this.

**Comment by AlbertoElias** [comment]
Yes, and you can also find which polyfills a module requires in its origami.json file https://github.com/Financial-Times/o-dom/blob/master/origami.json#L9
